### PR TITLE
Added methods post_jon and patch_json

### PR DESCRIPTION
**Pull request by uldisn**

### CODE REVIEW

**Comment by tcdent** [comment]
First, thanks for your contribution!

Please don't take this negatively, but I think you have misunderstood how to use this library. POST_JSON and PATCH_JSON are non-standard verbs, likely very specific in-use to your particular endpoint, and not something that should be included in this library. However, the goal of this library if configurability and extensibility, so here are a couple examples of how you can configure RestClient to work for your use case without modifying any of the base code. 

```
class JSONRestClient(RestClient) {
    public function __construct($options=array()){
        $default_options = array(
            'headers' => array(
                'Content-Type' => 'application/json'
            ));
        parent::__construct(array_merge($default_options, $options));
    }
    
    public function format_query($parameters, $primary=NULL, $secondary=NULL){
        return json_encode($parameters);
    }
}

$json_api = new JSONRestClient;

// Equivalent of your `post_json` method:
$result = $json_api->post("YOUR_RESOURCE_URL");


// Equivalent of your `patch_json` method:
$patch_api = clone $json_api;
$patch_api->set_option('curl_options', array(
    CURLOPT_POST => TRUE, 
    CURLOPT_CUSTOMREQUEST => 'PATCH'
));
$result = $patch_api->execute("YOUR_RESOURCE_URL", 'PATCH' array(), array(
    'X-HTTP-Method-Override' => 'PATCH'
));
```

**Comment by uldisn** [comment]
1. Configurability is good thing, but in this case it so complicate;
2. Usage POST JSON and PATCH JSON require standard libraries, what i use. That no my idea.

**Comment by uldisn** [comment]
There is other precedent: https://github.com/bssstudio/php-restclient/commit/96087a07e2291bed35878483895d04b8072c28b1

**Comment by tcdent** [comment]
Not adding new verbs, but I did make an update which I think you will appreciate. I also updated the documentation with some more information about your particular use case: https://github.com/tcdent/php-restclient#json-verbs

Here's the revised usage:

POST JSON
```
$result = $api->post("http://httpbin.org/post",
        json_encode(array('foo' => 'bar')),
        array('Content-Type' => 'application/json'));
```

PATCH JSON
```
$result = $api->execute("http://httpbin.org/patch", 'PATCH',
        json_encode(array('foo' => 'bar')),
        array(
            'X-HTTP-Method-Override' => 'PATCH', 
            'Content-Type' => 'application/json-patch+json'));
```

There's just too much ambiguity in the implementation particulars of these endpoints. Some may require `X-HTTP-Method-Override`, some may require `application/json` as the content type. This needs to be configured for each specific case. 

I also didn't find any documentation that stated the `CURL_POST` flag needed to be set for `PATCH` requests, so it remains enabled for `POST` only.

**Comment by uldisn** [comment]
Thanks!

Your suggested POST JSON passed PHPUNIT.
I delete my fork.

**Comment by tcdent** [comment]
> Your suggested POST JSON passed PHPUNIT.

Would you mind sharing any tests you have written? Writing some is next on my list.

**Comment by uldisn** [comment]
For testing I use my actual project API. 

```
    public function testApiClientRead() {

        $rop_api_header = [
                'Accept' => 'application/json',
                'Authorization' => '356yhgrdshgbredtfhfhbfxhgrfdhgffdga435555',
                ];
        $rop_api_url ='https://test.my.com/api/';

        $api = new RestClient([
            'base_url' => $rop_api_url,
            'headers' => $rop_api_header,
            'curl_options' => [
                CURLOPT_SSL_VERIFYPEER => false,
            ],
        ]);
        $result = $api->get("submission/instance/");

        $this->assertEquals($result->info->http_code, 200);

        $this->assertStringStartsWith('{', $result->response);
        $response_data = json_decode($result->response, true);
        $this->assertInternalType("int", $response_data['count']);
    }
    
    public function testApiClientPost() {
        $rop_api_header = [
                'Accept' => 'application/json',
                'Authorization' => '356yhgrdshgbredtfhfhbfxhgrfdhgffdga435555',
                ];
        $rop_api_url ='https://test.my.com/api/';

        /**
         * submit data
         */
        $data = [
            'form' => 10, //10 - konteinera izvešana, 9 konteinera ievešana
            'submitted_for' => date('Y-m-d'),
            'items' => [
                0 => [
                    "first_name" => 'Andris',
                    "last_name" => 'Bērziņs',
                    'number' => 'TEST NUMBER',
                ],
            ]
        ];

        $api = new RestClient([
            'base_url' => $rop_api_url,
            'headers' => $rop_api_header,
            'curl_options' => [
                CURLOPT_SSL_VERIFYPEER => false,
            ],
        ]);
        $result = $api->post("submission/instance/",
                json_encode($data),
                ['Content-Type' => 'application/json']);
        $this->assertEquals($result->info->http_code, 201);

        $response_data = json_decode($result->response, true);
        $this->assertInternalType("int", $response_data['id']);
       
    }
```

**Comment by tcdent** [comment]
Thanks for sharing!

**Pull request closed without merging**
