### PR TITLE
PHP8.1 Compatiblity

### PR DESCRIPTION
**Pull request by sheepfy**
Some coding standards + php8.1 compatiblity for methods:
offsetExists
offsetGet
offsetSet
offsetUnset

### CODE REVIEW

**Comment by tcdent** [comment]
Hi sheepfy!

I don't see anything actually functional changed in here; more of a personal style thing. 

I know some of my shorthand & formatting style is somewhat unconventional to some developers, but finding elegant solutions is what keeps me interested in PHP and this project in general all these years later.

**Comment by sheepfy** [comment]
Hi tcdent, the PR is not about the code formatting. We can leave that apart. It's about php8.1 compatibility. 
These methods: 
offsetExists
offsetGet
offsetSet
offsetUnset

Are not php8.1 compatible.

**Comment by tcdent** [comment]
I do have a PHP8 branch [1], but had to leave out a couple features to maintain compatibility with 7.x which a majority of users are still on [2]. I did test it, and the current release on 8.1 and found no problems. What specifically is incompatible?

Thanks for your efforts!

[1] https://github.com/tcdent/php-restclient/tree/php8
[2] https://packagist.org/packages/tcdent/php-restclient/php-stats

**Comment by tcdent** [comment]
I see now, you're talking about typing with `mixed` which isn't compatible with PHP7 afaik. Let me know if you're aware of a solution other than leaving the type absent.

**Pull request closed without merging**
